services:
  kitchen:
    build:
      context: ./kitchen
    container_name: kitchen-service
    restart: always
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - app-network

  warehouse:
    build:
      context: ./warehouse
    container_name: warehouse-service
    restart: always
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ui/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - app-network
  
  broker:
    image: apache/kafka:4.0.0
    container_name: broker
    restart: always
    ports:
      - "9092:9092"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
