export type InventoryEvent =
  | "CHECK_INGREDIENTS"
  | "PURCHASE_INGREDIENT"
  | "FULFILL_INGREDIENTS";

export const InventoryEvent = {
  CHECK_INGREDIENTS: "CHECK_INGREDIENTS",
  PURCHASE_INGREDIENT: "PURCHASE_INGREDIENT",
  FULFILL_INGREDIENTS: "FULFILL_INGREDIENTS",
};
