export type InventoryEvent =
  | "CHECK_INGREDIENTS"
  | "PURCHASE_INGREDIENT"
  | "UPDATE_STOCK";

export const InventoryEvent = {
  CHECK_INGREDIENTS: "CHECK_INGREDIENTS",
  PURCHASE_INGREDIENT: "PURCHASE_INGREDIENT",
  UPDATE_STOCK: "UPDATE_STOCK",
} as const;
